[package]
name = "rust-hdl-x"
version = "0.1.0"
edition = "2021"
description = "Experiments in RustHDL design and concepts"
authors = ["Samit Basu <basu.samit@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
num-traits = "0.2.15"
rust-hdl = { version = "0.46.0", path = "../rust-hdl" }
serde = { version = "1.0.171", features = ["derive"] }
vcd = "0.7.0"
