[package]
name = "rust-hdl-x"
version = "0.1.0"
edition = "2021"
description = "Experiments in RustHDL design and concepts"
authors = ["Samit Basu <basu.samit@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
bincode = "1.3.3"
colored-diff = "0.2.3"
indexmap = "2.0.0"
num-traits = "0.2.15"
proc-macro2 = "1.0.66"
quote = "1.0.31"
rust-hdl = { version = "0.46.0", path = "../rust-hdl" }
rust-hdl-x-macro = { version = "0.1.0", path = "../rust-hdl-x-macro" }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.105"
syn = { version = "2.0.26", features = ["full"] }
vcd = "0.7.0"
