[package]
name = "rust-hdl-vcd-plot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.10.0"
num-bigint = "0.4.3"
substring = "1.4.5"