[workspace]

members = [
    "rust-hdl-core",
    "rust-hdl-macros",
    "rust-hdl-test",
    "rust-hdl-widgets",
    "rust-hdl-yosys-synth",
    "rust-hdl-bsp-alchitry-cu",
    "rust-hdl-pcb",
    "rust-hdl-ok-frontpanel-sys",
    "rust-hdl-pcb-core",
    "rust-hdl-pcb-svg",
    "rust-hdl-pcb-kicad",
    "rust-hdl-pcb-schematic-layout-tool",
    "rust-hdl-ok-widgets",
    "rust-hdl-sim-chips",
    "rust-hdl-bsp-ok-xem6010",
    "rust-hdl-bsp-ok-xem7010",
]
