[workspace]

members = [
    "rust-hdl",
    "rust_hdl_private_core",
    "rust_hdl_private_hls",
    "rust_hdl_private_sim",
    "rust_hdl_private_widgets",
    "rust_hdl_private_macros",
    "rust_hdl_private_ok_core",
    "rust_hdl_private_bsp_alchitry_cu",
    "rust_hdl_private_bsp_ok_xem6010",
    "rust_hdl_private_bsp_ok_xem7010",
    "rust_hdl_private_fpga_support",
]
