[workspace]

members = [
    "rust-hdl",
    "rust_hdl_core",
    "rust_hdl_hls",
    "rust_hdl_sim",
    "rust_hdl_widgets",
    "rust_hdl_macros",
    "rust_hdl_ok_core",
    "rust_hdl_fpga_support",
    "rust-hdl-bsp-alchitry-cu",
    "rust-hdl-bsp-ok-xem6010",
    "rust-hdl-bsp-ok-xem7010",
]
