[workspace]

members = [
    "rust-hdl",
    "rust_hdl__core",
    "rust_hdl__hls",
    "rust_hdl__sim",
    "rust_hdl__widgets",
    "rust_hdl__macros",
    "rust_hdl__ok_core",
    "rust_hdl__bsp_alchitry_cu",
    "rust_hdl__bsp_ok_xem6010",
    "rust_hdl__bsp_ok_xem7010",
    "rust_hdl__fpga_support",
]
