[workspace]

members=["rust-hdl",
    "rust-hdl-macros",
    "rust-hdl-ok-core",
    "rust-hdl-bsp-alchitry-cu",
    "rust-hdl-bsp-ok-xem6010",
    "rust-hdl-bsp-ok-xem7010",
    "rust-hdl-fpga-support"]
