[workspace]

members = [
    "rust-hdl",
    "rust_hdl_core",
    "rust_hdl_hls",
    "rust_hdl_sim",
    "rust_hdl_widgets",
    "rust_hdl_macros",
    "rust_hdl_ok_core",
    "rust_hdl_bsp_alchitry_cu",
    "rust_hdl_bsp_ok_xem6010",
    "rust_hdl_bsp_ok_xem7010",
    "rust_hdl_fpga_support",
]
