[package]
name = "rust_hdl_private_macros"
version = "0.44.0"
edition = "2018"
license = "MIT"
description = "Macro support for RustHDL"
homepage = "https://github.com/samitbasu/rust-hdl"
repository = "https://github.com/samitbasu/rust-hdl"
keywords = ["fpga", "verilog", "hardware"]
authors = ["Samit Basu <samit.basu@smiths.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.73", features = ["full", "extra-traits", "visit"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"
regex = "1.3.4"
