[package]
name = "rust-hdl-schem-layout"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.13.1"
epi = "0.13.0"
rust-hdl-pcb = {path="../rust-hdl-pcb"}
serde_json = "^1"
