[package]
name = "rust_hdl_core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_hdl_macros = {path="../rust-hdl-macros"}
crossbeam = "0.8.1"
num-bigint = "0.4.0"

