[package]
name = "rust_hdl_alchitry_cu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_hdl_core = {path="../rust-hdl-core"}
rust_hdl_synth = {path= "../rust-hdl-yosys-synth" }

