[package]
name = "rust-hdl-bsp-ok-xem6010"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-hdl = {path="../rust-hdl", version="^0.31.0"}
rust-hdl-fpga-support = {path="../rust-hdl-fpga-support", version="^0.1.0"}
rust-hdl-ok-core = {path="../rust-hdl-ok-core", version="^0.4.0"}
rust-hdl-ok-frontpanel-sys = {path="../rust-hdl-ok-frontpanel-sys", version="^0.2.0"}
rand = {version="0.8.1"}
