[package]
name = "rust-hdl-bsp-ok-xem7010"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Board Support Package for OpalKelly XEM7010 module for RustHDL crate."
homepage = "https://rusthdl.org"
repository = "https://github.com/SmithsDigitalForge/rust-hdl"
keywords = ["fpga", "verilog", "hardware"]
authors = ["Samit Basu <samit.basu@smiths.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-hdl-core = "^0.1"
rust-hdl-toolchain-vivado = "^0.1"
rust-hdl-ok-core = "^0.1"
rust-hdl-widgets = "^0.1"
rust-hdl-yosys-synth = "^0.1"

[dev-dependencies]
rust-hdl-test-ok-common = "^0.1"
rust-hdl-ok-frontpanel-sys = "^0.1"
rust-hdl-test-core = "^0.1"
rand = "0.8.4"