[package]
name = "rust-hdl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-hdl-core = {path="../rust-hdl-core"}
rust-hdl-macros = {path="../rust-hdl-macros"}
rust-hdl-widgets = {path="../rust-hdl-widgets"}
rust-hdl-yosys-synth = {path="../rust-hdl-yosys-synth"}
rust-hdl-bsp-ok-xem6010 = {path="../rust-hdl-bsp-ok-xem6010", optional=true}
rust-hdl-bsp-ok-xem7010 = {path="../rust-hdl-bsp-ok-xem7010", optional=true}
rust-hdl-ok-core = {path="../rust-hdl-ok-core", optional=true}
rust-hdl-toolchain-common = {path="../rust-hdl-toolchain-common", optional=true}
rust-hdl-toolchain-ise = {path="../rust-hdl-toolchain-ise", optional=true}
rust-hdl-toolchain-vivado = {path="../rust-hdl-toolchain-vivado", optional=true}
rust-hdl-toolchain-icestorm = {path="../rust-hdl-toolchain-icestorm", optional=true}
rust-hdl-sim-chips = {path="../rust-hdl-sim-chips", optional=true}
rust-hdl-bsp-alchitry-cu = {path="../rust-hdl-bsp-alchitry-cu", optional=true}
rust-hdl-test-core = {path="../rust-hdl-test-core", optional=true}
rust-hdl-test-ok-common = {path="../rust-hdl-test-ok-common", optional=true}


[features]
default = ["ok", "sim", "ise", "vivado", "icestorm", "alchitry_cu", "test_tools"]
ok = ["rust-hdl-bsp-ok-xem6010", "rust-hdl-bsp-ok-xem7010", "rust-hdl-ok-core", "rust-hdl-test-ok-common"]
sim = ["rust-hdl-sim-chips"]
ise = ["rust-hdl-toolchain-ise", "rust-hdl-toolchain-common"]
vivado = ["rust-hdl-toolchain-vivado", "rust-hdl-toolchain-common"]
icestorm = ["rust-hdl-toolchain-icestorm", "rust-hdl-toolchain-common"]
alchitry_cu = ["rust-hdl-bsp-alchitry-cu"]
test_tools = ["rust-hdl-test-core"]