[package]
name = "rust-hdl"
version = "0.41.1"
edition = "2018"
license = "MIT"
description = "Write firmware for FPGAs in Rust"
homepage = "http://rust-hdl.org"
repository = "https://github.com/SmithsDigitalForge/rust-hdl"
keywords = ["fpga", "verilog", "hardware"]
authors = ["Samit Basu <samit.basu@smiths.com>"]

[dependencies]
rust-hdl-macros = {version= "^0.24.0", path="../rust-hdl-macros"}
crossbeam = "0.8.1"
num-bigint = "0.4.0"
num-traits = "0.2.14"
vcd = "0.6.1"
evalexpr = "6.3.0"
regex = "1.5.4"
array-init = "2.0.0"
rand = "0.8"
petgraph = "0.6.0"
embed-doc-image = "0.1.4"
svg = "0.10.0"
substring = "^1"
anyhow = "^1"

seq-macro = "0.3.1"
