[package]
name = "rust-hdl"
version = "0.15.0"
edition = "2018"
license = "MIT"
description = "Write firmware for FPGAs in Rust"
homepage = "https://rusthdl.org"
repository = "https://github.com/SmithsDigitalForge/rust-hdl"
keywords = ["fpga", "verilog", "hardware"]
authors = ["Samit Basu <samit.basu@smiths.com>"]

[dependencies]
rust-hdl-macros = "^0.10.1"
#rust-hdl-macros = {version="0.10.1", path="../rust-hdl-macros"}
crossbeam = "0.8.1"
num-bigint = "0.4.0"
num-traits = "0.2.14"
vcd = "0.6.1"
evalexpr = "6.3.0"
regex = "1.5.4"
array-init = "2.0.0"
rust-hdl-ok-frontpanel-sys = {version="^0.2", optional=true}
rand = "0.8"

[features]
frontpanel = ["rust-hdl-ok-frontpanel-sys"]
