[package]
name = "rust-hdl"
version = "0.2.0"
edition = "2018"
license = "MIT"
description = "Write firmware for FPGAs in Rust"
homepage = "https://rusthdl.org"
repository = "https://github.com/SmithsDigitalForge/rust-hdl"
keywords = ["fpga", "verilog", "hardware"]
authors = ["Samit Basu <samit.basu@smiths.com>"]

[dependencies]
#rust-hdl-macros = "^0.1"
#rust-hdl-widgets = "^0.1"
#rust-hdl-yosys-synth = "^0.1"
#rust-hdl-bsp-ok-xem6010 = {version="^0.1", optional=true}
#rust-hdl-bsp-ok-xem7010 = {version="^0.1", optional=true}
#rust-hdl-ok-core = {version="^0.1", optional=true}
#rust-hdl-toolchain-common = {version="^0.1", optional=true}
#rust-hdl-toolchain-ise = {version="^0.1", optional=true}
#rust-hdl-toolchain-vivado = {version="^0.1", optional=true}
#rust-hdl-toolchain-icestorm = {version="^0.1", optional=true}
#rust-hdl-sim-chips = {version="^0.1", optional=true}
#rust-hdl-bsp-alchitry-cu = {version="^0.1", optional=true}
#rust-hdl-test-core = {version="^0.1", optional=true}
#rust-hdl-test-ok-common = {version="^0.1", optional=true}
rust-hdl-ok-frontpanel-sys = {version="^0.1", optional=true}

rust-hdl-macros = "^0.1.0"
crossbeam = "0.8.1"
num-bigint = "0.4.0"
vcd = "0.6.1"
evalexpr = "6.3.0"
regex = "1.5.4"
array-init = "2.0.0"




#[features]
#default = ["sim", "test_tools"]
#ok = ["rust-hdl-bsp-ok-xem6010", "rust-hdl-bsp-ok-xem7010", "rust-hdl-ok-core", "rust-hdl-test-ok-common", "rust-hdl-ok-frontpanel-sys"]
#sim = ["rust-hdl-sim-chips"]
#ise = ["rust-hdl-toolchain-ise", "rust-hdl-toolchain-common"]
#vivado = ["rust-hdl-toolchain-vivado", "rust-hdl-toolchain-common"]
#icestorm = ["rust-hdl-toolchain-icestorm", "rust-hdl-toolchain-common"]
#alchitry_cu = ["rust-hdl-bsp-alchitry-cu"]
#test_tools = ["rust-hdl-test-core"]